const fs = require('fs');
const path = require('path');

module.exports = {
    name: 'chart',
    alias: ['graph', 'plot', 'bargraph'],
    category: 'Documents',
    desc: 'Generate an ASCII bar chart',
    usage: '.chart Title | label1:value1 | label2:value2 | label3:value3',

    execute: async (sock, m, { args, reply }) => {
        const input = args.join(' ').trim();
        if (!input) return reply('⚉ Usage: .chart Sales | Jan:100 | Feb:250 | Mar:180 | Apr:300');

        const parts = input.split('|').map(p => p.trim());
        if (parts.length < 2) return reply('_*⚉ Provide title and at least one data point*_');

        const title = parts[0];
        let maxVal = 0;
        const data = [];

        parts.slice(1).forEach(p => {
            const match = p.match(/^(.+):(\d+)$/);
            if (match) {
                const val = parseInt(match[2]);
                data.push({ label: match[1].trim(), value: val });
                if (val > maxVal) maxVal = val;
            }
        });

        if (!data.length) return reply('_*⚉ No valid data found*_');

        const barWidth = 20;
        let chart = `${title}\n${'═'.repeat(40)}\n`;

        data.forEach(d => {
            const fill = Math.round((d.value / maxVal) * barWidth);
            const bar = '█'.repeat(fill) + '░'.repeat(barWidth - fill);
            chart += `${d.label.padEnd(8)} │${bar} ${d.value}\n`;
        });

        chart += `${'═'.repeat(40)}\nGenerated by CRYSNOVA AI`;

        const tempDir = path.join(__dirname, '../../temp');
        if (!fs.existsSync(tempDir)) fs.mkdirSync(tempDir, { recursive: true });
        const filePath = path.join(tempDir, `chart_${Date.now()}.txt`);
        fs.writeFileSync(filePath, chart);

        await sock.sendMessage(m.chat, {
            document: fs.readFileSync(filePath),
            fileName: `${title}_chart.txt`,
            mimetype: 'text/plain',
            caption: `📊 Chart: ${title}`
        }, { quoted: m });

        fs.unlinkSync(filePath);
    }
};
