module.exports = {
    name: 'table',
    alias: ['tbl', 'grid'],
    category: 'Documents',
    desc: 'Generate a table in chat',
    usage: '.table Title | H1,H2,H3 | R1C1,R1C2,R1C3',

    execute: async (sock, m, { args, reply }) => {
        const input = args.join(' ').trim();
        if (!input) return reply('⚉ Usage: .table Students | Name,Age,Grade | John,25,A | Jane,30,B');

        const parts = input.split('|').map(p => p.trim());
        if (parts.length < 2) return reply('_*⚉ Provide title and data rows*_');

        const title = parts[0];
        const rows = parts.slice(1);

        // Build table data for WhatsApp native table
        const tableData = [];
        
        rows.forEach((row, i) => {
            const cols = row.split(',').map(c => c.trim());
            tableData.push(cols);
        });

        await sock.sendMessage(m.chat, {
            headerText: `## 📊 ${title}`,
            contentText: '---',
            title: `${rows.length} Row${rows.length > 1 ? 's' : ''}`,
            table: tableData,
            footerText: '💡 Generated by CRYSNOVA AI'
        }, { quoted: m });
    }
};
