const axios = require('axios');

module.exports = {
    name: 'brat',
    alias: [],
    desc: 'Create a Brat-style image with text',
    category: 'Maker',
    usage: '.brat <text>',
    reactions: { start: '🎬', success: '✨', error: '🎭' },

    execute: async (sock, m, { args, reply }) => {
        const text = args.join(' ').trim();
        
        if (!text) {
            return reply(
                `╭─❍ *BRAT MAKER*\n│\n` +
                `│ ⚉ *Usage:* .bratvid <text>\n│\n` +
                `│ ✪ *Example:*\n` +
                `│ .brat Hello\n` +
                `│ .brat CRYSNOVA AI\n│\n` +
                `│ 🎨 *Creates Brat-style image*\n` +
                `╰──────────────────`
            );
        }

        await sock.sendMessage(m.chat, { react: { text: '🎬', key: m.key } });

        try {
            const response = await axios.get('https://api.zenzxz.my.id/maker/bratvid', {
                params: { text: text },
                responseType: 'arraybuffer',
                timeout: 30000
            });

            const contentType = response.headers['content-type'] || 'unknown';
            const buffer = Buffer.from(response.data);

            // Check if response is valid image/video data (not HTML/JSON error)
            const isValidMedia = (
                contentType.includes('image') ||
                contentType.includes('video') ||
                contentType.includes('octet-stream') ||
                contentType.includes('gif') ||
                buffer.slice(0, 6).toString() === 'GIF89a' ||  // GIF magic bytes
                buffer.slice(0, 8).toString('hex') === '89504e470d0a1a0a' ||  // PNG
                buffer.slice(0, 3).toString('hex') === 'ffd8ff'  // JPEG
            );

            if (!isValidMedia) {
                const errorText = buffer.toString().slice(0, 500);
                await sock.sendMessage(m.chat, { react: { text: '🔖', key: m.key } });
                return reply(`\`✘ API returned invalid data:\` ${errorText || 'Empty response'}`);
            }

            if (buffer.length < 100) {
                await sock.sendMessage(m.chat, { react: { text: '🔖', key: m.key } });
                return reply(`\`✘ Media data too small or corrupted\` (${buffer.length} bytes)`);
            }

            // Send as image (works for GIF too)
            await sock.sendMessage(m.chat, {
                image: buffer,
            //    caption: `🎨 *Brat:* ${text}\n\n_⚉ Generated by CRYSNOVA AI_`
            },);

            await sock.sendMessage(m.chat, { react: { text: '👌', key: m.key } });

        } catch (error) {
            await sock.sendMessage(m.chat, { react: { text: '❔', key: m.key } });
            
            if (error.code === 'ECONNABORTED') {
                return reply('`✘ Request timed out. Try again.`');
            }

            if (error.response) {
                const status = error.response.status;
                const errorData = Buffer.from(error.response.data || '').toString().slice(0, 300);
                return reply(`\`✘ API Error ${status}:\` ${errorData || 'Unknown error'}`);
            }

            if (error.request) {
                return reply('`✘ No response from API. Service may be down.`');
            }

            reply(`\`✘ ${error.message || 'Failed to create Brat image'}\``);
        }
    }
};

